name: "photo_content_front"
services:
  nginx:
    image: nginx:latest
    volumes:
      - app_data:/var/www/html
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - front_network
  app:
    image: alonecat/photo_content_front:latest
    ports:
      - "4173:4173"
    volumes:
      - app_data:/var/www/html
    networks:
      - front_network
    environment:
      NODE_ENV: production

networks:
  front_network:
    driver: bridge

volumes:
  app_data:
