name: client

services:
  app-client:
    build:
      context: .
      dockerfile: .deploy/Dockerfile
    restart: unless-stopped
    networks:
      -  content_host_network
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: ${NODE_ENV}
      VITE_BASE_URL: ${VITE_BASE_URL}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-client.rule=Host(`gallery.24contenthost.ru`)"
      - "traefik.http.routers.app-client.entrypoints=websecure"
      - "traefik.http.routers.app-client.tls.certresolver=letsencrypt"

networks:
  content_host_network:
    external: true


