name: client

services:
  app-client:
    build:
      context: .
      dockerfile: .deploy/Dockerfile
    restart: unless-stopped
    networks:
      -  content_host_network
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: ${NODE_ENV}
      VITE_BASE_URL: ${VITE_BASE_URL}

networks:
  content_host_network:
    external: true

#volumes:
  #app_data:
