name: Build and Push Docker Image and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Create .env.production file
        run: |
          echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}" > .env.production

      - name: Build and push Docker image for prod
        run: |
          docker build -f _docker/Dockerfile --build-arg VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }} -t alonecat/photo_content_front:latest .
          docker push alonecat/photo_content_front:latest
  deploy:
    runs-on: ["self-hosted", "vps-frontend"]
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy to vps
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}

        run: |
          echo "NODE_ENV=${NODE_ENV}"
          echo "VITE_API_BASE_URL=${VITE_API_BASE_URL}"
          
          echo "Pulling latest Docker image..."
          docker pull alonecat/photo_content_front:latest

          docker-compose -f docker-compose.prod.yml down --volumes --remove-orphans
          sleep 5
          docker-compose -f docker-compose.prod.yml up -d

          echo "Deployment completed successfully!"
